-d /home/arielo/repos/SD/Proyecto_Paint/main/impl/gwsynthesis/project.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst /home/arielo/repos/SD/Proyecto_Paint/main/constraints/sipeed_tang_primer_25k.cst
-cfg /home/arielo/repos/SD/Proyecto_Paint/main/impl/pnr/device.cfg
-sdc /home/arielo/repos/SD/Proyecto_Paint/main/constraints/sipeed_tang_primer_25k.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
